# Generated by Django 2.2.6 on 2019-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
    ]
