# Generated by Django 2.2.6 on 2019-11-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0006_remove_club_earned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
    ]
