# Generated by Django 2.2.6 on 2019-11-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0007_club_earned_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molekulam', to='kpl.Club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salam', to='kpl.Club')),
            ],
        ),
    ]
