# Generated by Django 2.2.6 on 2019-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0008_gamecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecycle',
            name='tour_id',
            field=models.IntegerField(default=1),
        ),
    ]
