# Generated by Django 2.2.6 on 2019-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0009_gamecycle_tour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='started_points',
            field=models.IntegerField(default=0),
        ),
    ]
