# Generated by Django 2.2.6 on 2019-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0011_euclub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EUClub',
            new_name='Eu_club',
        ),
    ]
