# Generated by Django 2.2.6 on 2019-11-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0012_auto_20191123_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_club',
            name='tournament_played',
            field=models.CharField(default='UCL', max_length=100),
        ),
    ]
