# Generated by Django 2.2.6 on 2019-11-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0013_auto_20191123_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eu_club',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='eu_club',
            name='goals_scored',
        ),
        migrations.AddField(
            model_name='eu_club',
            name='goal_difference',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
