# Generated by Django 2.2.6 on 2019-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0014_auto_20191123_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='eu_club',
            name='group',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
