# Generated by Django 2.2.6 on 2019-11-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0015_eu_club_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eu_cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_played', models.CharField(default=0, max_length=100)),
                ('group', models.CharField(default=0, max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molekulam', to='kpl.Eu_club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salam', to='kpl.Eu_club')),
            ],
        ),
    ]
