# Generated by Django 2.2.6 on 2019-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0017_eu_cycle_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_cycle',
            name='group',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='eu_cycle',
            name='tournament_played',
            field=models.CharField(default='UCL', max_length=100),
        ),
    ]
