# Generated by Django 2.2.6 on 2019-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0018_auto_20191125_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_cycle',
            name='tournament_played',
            field=models.CharField(default='UEL', max_length=100),
        ),
    ]
