# Generated by Django 2.2.6 on 2019-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0021_auto_20191125_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_cycle',
            name='group',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
