# Generated by Django 2.2.6 on 2019-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0022_auto_20191125_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_cycle',
            name='group',
            field=models.CharField(default='E', max_length=1),
        ),
    ]
