# Generated by Django 2.2.6 on 2019-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0030_auto_20191125_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('season15_16', models.IntegerField(default=0, null=True)),
                ('season16_17', models.IntegerField(default=0, null=True)),
                ('season17_18', models.IntegerField(default=0, null=True)),
                ('season18_19', models.IntegerField(default=0, null=True)),
                ('season19_20', models.IntegerField(default=0, null=True)),
                ('total_rating', models.IntegerField(default=0, null=True)),
                ('command_count', models.CharField(max_length=7)),
            ],
        ),
    ]
