# Generated by Django 2.2.6 on 2019-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0031_ratingcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcountry',
            name='place',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
