# Generated by Django 2.2.6 on 2019-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpl', '0032_ratingcountry_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcountry',
            name='season15_16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcountry',
            name='season16_17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcountry',
            name='season17_18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcountry',
            name='season18_19',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcountry',
            name='season19_20',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcountry',
            name='total_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
