# Generated by Django 2.2.6 on 2019-10-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200, verbose_name='Title of the news')),
                ('news_sh_description', models.CharField(max_length=800, verbose_name='Short description of the news')),
                ('news_content', models.TextField(verbose_name='Content of the news')),
                ('publication_date', models.DateTimeField(verbose_name='Date of publication of the news')),
                ('count_of_views', models.IntegerField(verbose_name='Count of views of the news')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200, verbose_name='Author of the comment')),
                ('comment_text', models.TextField(verbose_name='Content of comment')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
    ]
