# Generated by Django 2.2.6 on 2019-11-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_news_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liked_post_ID', to='news.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID_Liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
