# Generated by Django 2.2.6 on 2019-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_tag',
            field=models.CharField(choices=[('A', 'Другое'), ('K', 'Казахстанская-премьер лига'), ('NT', 'Национальная сборная по футболу'), ('UCL', 'Лига чемпионов УЕФА'), ('UEL', 'Лига Европы УЕФА')], default='A', max_length=1),
        ),
    ]
