# Generated by Django 2.2.6 on 2019-12-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191128_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of the news'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Text of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='count_of_views',
            field=models.IntegerField(verbose_name='Count of views'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Title photo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Count of likes'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of the news'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/defavatar.jpg', null=True, upload_to='images/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Birthday Date'),
        ),
    ]
