# Generated by Django 2.2.6 on 2019-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191029_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_tag',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Казахстанская-премьер лига', 'Казахстанская-премьер лига'), ('Национальная сборная по футболу', 'Национальная сборная по футболу'), ('Лига чемпионов УЕФА', 'Лига чемпионов УЕФА'), ('Лига Европы УЕФА', 'Лига Европы УЕФА')], default='Другое', max_length=100),
        ),
    ]
