# Generated by Django 2.2.6 on 2019-11-12 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20191101_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fav_news_ID', to='news.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_ID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
