# Generated by Django 2.2.6 on 2019-11-13 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 13, 5, 46, 46, 73227, tzinfo=utc), null=True),
        ),
    ]
