# Generated by Django 2.2.6 on 2019-11-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20191113_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='defavatar.jpg', null=True, upload_to='images/avatars'),
        ),
    ]
