# Generated by Django 2.2.6 on 2019-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20191113_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/defavatar.jpg', null=True, upload_to='images/avatars/'),
        ),
    ]
