# Generated by Django 2.2.6 on 2019-11-17 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
