# Generated by Django 2.2.6 on 2019-11-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20191117_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_author',
        ),
    ]
