# Generated by Django 2.2.6 on 2019-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
                ('count_of_wins', models.IntegerField(default=0)),
                ('count_of_draws', models.IntegerField(default=0)),
                ('count_of_loses', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('earned_points', models.IntegerField(default=0)),
                ('started_points', models.IntegerField(default=0)),
            ],
        ),
    ]
