# Generated by Django 2.2.6 on 2019-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='euclub',
            name='tournament_played',
            field=models.CharField(default='UEL', max_length=100),
        ),
    ]
